# app/config/security.yml
security:
    encoders:
        FOS\UserBundle\Model\UserInterface: plaintext

    role_hierarchy:
        ROLE_SUPER_ADMIN: ROLE_ADMIN
        ROLE_APPRENANT: ROLE_USER
        ROLE_FORMATEUR: ROLE_USER
        ROLE_MEMBRE_COMITE: ROLE_USER
        ROLE_ENTREPRISE: ROLE_USER

    providers:
        fos_userbundle:
            id: fos_user.user_provider.username

    firewalls:
        main:
            pattern: ^/
            form_login:
                provider: fos_userbundle
                csrf_provider: form.csrf_provider
                success_handler: redirect.after.login

            logout:      
                path: /logout
                target: /
                success_handler: redirect.after.logout
        
            anonymous: true

    access_control:
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin/, role: ROLE_ADMIN }
        - { path: ^/liste_apprenant, role: ROLE_SUPER_ADMIN }
        - { path: ^/liste_formateur, role: ROLE_SUPER_ADMIN }
        - { path: ^/liste_membre_comite, role: ROLE_SUPER_ADMIN }
        - { path: ^/liste_ins_entreprise, role: ROLE_SUPER_ADMIN }
        - { path: ^/espace_admin, role: ROLE_SUPER_ADMIN }
        - { path: ^/espace_formateur, role: ROLE_FORMATEUR }